# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.16.14
loom_version=1.11-SNAPSHOT
# https://masa.dy.fi/maven/carpet/fabric-carpet/
# carpet_core_version=1.18-1.4.56+v211130

# Mod Properties
mod_version = 1.4.2
maven_group = cn.focot.codelab
archives_base_name = MineCodeCraftMod

# Dependencies
fabric_version=0.131.0+1.21.8
nats_version=2.21.4
